SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;

BEGIN

SELECT count(*) into nCount FROM user_tables where table_name = 'PATIENT';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('PATIENT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PATIENT
            (	
            patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
            first_name varchar2(50) NOT NULL,
            last_name varchar2(50) NOT NULL,
            address_line1 varchar2(50) NOT NULL,
            address_line2 varchar2(50) NOT NULL,
            city varchar2(20),
            zip number(5) NOT NULL,
            state_name varchar2(3),
            DOB date,
            contact_no number(10),
            email_id VARCHAR2(40),
            SSN number(9) NOT NULL,
            CONSTRAINT restrict_ploc CHECK (state_name IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')),
            CONSTRAINT patient_id PRIMARY KEY(patient_id),
            CONSTRAINT ssn_unique UNIQUE(SSN),
            CONSTRAINT email_chk CHECK (email_id LIKE ''%@%.%'' AND email_id NOT LIKE ''@%'' AND email_id NOT LIKE ''%@%@%'')
            )';
    DBMS_OUTPUT.PUT_LINE('PATIENT TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''tina'',''natekar'',''2 torpie street'',''apt-1'',''boston'',02120,''MA'',TO_DATE(''1998/06/03'', ''yyyy/mm/dd''),4766443677,''tina@gmail.com'',312829898)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''miranda'',''tate'',''89 Huntington street'',''apt-13'',''Dayton'',021320,''OH'',to_date(''03.02.1988'',''mm/dd/yyyy''),4762134677,''mir@gmail.com'',792353679)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''nina'',''dobrev'',''smith street'',''apt-3'',''boston'',98765,''MA'',to_date(''08.12.1991'',''mm/dd/yyyy''),8576423132,''nina@gmail.com'',348576338)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''tyler'',''smith'',''56 va medical center'',''apt-89'',''baltimore'',01115,''MA'',to_date(''01.08.1998'',''mm/dd/yyyy''),8573179680,''smith@gmail.com'',294755093)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''steve'',''warner'',''13 heath street'',''apt-46'',''boston'',09800,''MA'',to_date(''01.06.1989'',''mm/dd/yyyy''),5642356446,''steve@gmail.com'',485764767)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''marcus'',''stoinis'',''10 horadon way'',''apt-199'',''houston'',01219,''TX'',to_date(''01.03.1991'',''mm/dd/yyyy''),9877746536,''ms@gmail.com'',498570909)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''jaina'',''abideen'',''988 gargoil street'',''apt-76'',''san diego'',028810,''CA'',to_date(''09.10.2001'',''mm/dd/yyyy''),992292250,''jainahero@gmail.com'',948567878)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''ross'',''gallor'',''1 hemenway street'',''apt-34'',''boston'',02115,''MA'',to_date(''12.12.1988'',''mm/dd/yyyy''),7566677769,''ross@yahoo.com'',298341198)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''virat'',''kohli'',''75 st alhonsus'',''apt-816'',''boston'',02120,''MA'',to_date(''09.30.1998'',''mm/dd/yyyy''),3571536757,''virat70@gmail.com'',198342541)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Thibau'',''courtouis'',''13 santiago bernabeu street'',''apt-1'',''roxbury'',02119,''MA'',to_date(''12.19.1987'',''mm/dd/yyyy''),6179924681,''t.coutouis@outlook.com'',984561901)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''David'',''Alaba'',''04 wakulah street'',''apt-13'',''boston'',02120,''MA'',to_date(''09.09.1985'',''mm/dd/yyyy''),9443916852,''david04@yahoo.co.in'',791037891)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Eder'',''Militao'',''22 washington street'',''apt-29'',''Roxbury'',02119,''MA'',to_date(''06.24.1992'',''mm/dd/yyyy''),9443442747,''edermilitao0335@gmail.com'',487561517)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Ferland'',''Mendy'',''44 park drive street'',''apt-3'',''boston'',98765,''MA'',to_date(''04.21.1992'',''mm/dd/yyyy''),9486612364,''mendy.f@realmadrid.com'',983210908)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Dani'',''Carvajal'','' 02 bay state place'',''apt-2014'',''boston'',02127,''MA'',to_date(''05.17.1998'',''mm/dd/yyyy''),9443913624,''danic2@gmail.com'',249784468)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Tony'',''Kroos'',''13 heath street'',''apt-23'',''boston'',02120,''MA'',to_date(''06.14.1974'',''mm/dd/yyyy''),9443321323,''kroos_toni8@gmail.com'',798624678)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Tom'',''Arthur'',''28 Pleasant Street'',''Unit 1'',''Medford'',2823,''MA'',to_date(''12-AUG-80'',''DD-MON-RR''),9687326782,''tom.arthur@gmail.com'',124809452)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Mark'',''Tully'',''1 Stonegate Road'',''Apt 1'',''Erie'',89792,''IL'',to_date(''18-APR-65'',''DD-MON-RR''),7978998240,''mark.tully@gmail.com'',457621364)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Sally'',''Soline'',''39 Prospect Steet'',''39'',''Worcester'',29842,''MA'',to_date(''24-MAY-83'',''DD-MON-RR''),8978902394,''sally.s24@gmail.com'',496257245)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Robin'',''Severe'',''4 Etna Street'',''Apt 40'',''Austin'',89734,''TX'',to_date(''31-DEC-03'',''DD-MON-RR''),8934074079,''r.severe@gmail.com'',531265357)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Hammad'',''Nina'',''Dustin Street'',''Apt 39'',''Bloomsfield'',98424,''WY'',to_date(''08-APR-94'',''DD-MON-RR''),8972740845,''nina.hammad@gmail.com'',324657246)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Derek'',''Mahavir'',''38 Broadwalk'',''Unit 45'',''Los Angeles'',2378,''CA'',to_date(''20-FEB-21'',''DD-MON-RR''),9837908490,''derek.maha@ymail.com'',567986796)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Peter'',''Tiernan'',''Miller Street'',''54'',''San Diego'',90854,''CA'',to_date(''30-DEC-14'',''DD-MON-RR''),7897598753,''ptierman@gmail.com'',468946875)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Joseph'',''Khazhak'',''290 Western Ave'',''Apt 3'',''Cambridge'',89349,''MA'',to_date(''01-JUN-18'',''DD-MON-RR''),7249575979,''joe.khazhak@gmail.com'',935765357)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Gervasius'',''Emelrich'',''30 Dalton'',''Apt 54'',''Queens'',83904,''NY'',to_date(''16-DEC-97'',''DD-MON-RR''),7894793495,''gerva.emelrich@gmail.com'',356546467)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Dayton'',''Nudd'',''80 Middle River Court'',''Apt 3'',''Southborogh'',42565,''WA'',to_date(''17-JUL-00'',''DD-MON-RR''),4830845345,''nudd.d@gmail.com'',456583574)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Liubov'',''Steinarr'',''7043 Union Drive'',''U-24'',''Westford'',34545,''MI'',to_date(''23-MAR-56'',''DD-MON-RR''),7673467467,''liu.steinarr@rediff.com'',976465735)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Archana'',''Kochar'',''77 Foster Drive'',''Unit 21'',''Norwood'',52464,''GA'',to_date(''21-JAN-04'',''DD-MON-RR''),4676889767,''kochar.archana@gmail.com'',754646754)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Rosalie'',''Castor'',''592 Lookout Street'',''Apt 2'',''Riverdale'',13345,''HI'',to_date(''01-MAR-87'',''DD-MON-RR''),4576787686,''rosecastor@gmail.com'',357567745)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Simin'',''Mawar'',''96 Forest Road'',''Apt 12'',''Riverside'',67534,''NC'',to_date(''10-JAN-01'',''DD-MON-RR''),8867678967,''smith.mawar@gmail.com'',867878957)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Orhan'',''Eulalia'',''6 Edgemont Street'',''Apt 3'',''Foxborough'',33564,''OK'',to_date(''27-JUN-65'',''DD-MON-RR''),8246546845,''orhan.eulalia@gmail.com'',546456876)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Alys'',''Prasad'',''9714 Pendergast Street'',''Apt 2'',''Stoughton'',76523,''DE'',to_date(''21-NOV-21'',''DD-MON-RR''),8984634343,''prasad.alys@gmail.com'',458985798)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Shamsuddin'',''Em'',''197 Railroad Street'',''Apt 24'',''Medfield'',75234,''FL'',to_date(''15-APR-99'',''DD-MON-RR''),8787563234,''sham.em@gmail.com'',878967896)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Quintis'',''Armida'',''209 High Noon Drive'',''Apt 5'',''Millis'',75623,''TX'',to_date(''09-SEP-20'',''DD-MON-RR''),9790965778,''quintis.armida@gmail.com'',345756856)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Nuallan'',''Doirend'',''239 Charles Court'',''Apt 99'',''Sherborn'',78634,''DE'',to_date(''23-JAN-60'',''DD-MON-RR''),8909084523,''nuallan.doiren@gmail.com'',435889076)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Siri'',''Euclides'',''9040 Pacific Drive'',''Apt 2'',''Marlborough'',46235,''MO'',to_date(''06-MAY-74'',''DD-MON-RR''),7056787463,''siri.euclides@gmail.com'',346576788)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Pharez'',''Christen'',''1 Howard Drive'',''Apt 6'',''Hudson'',65723,''KY'',to_date(''14-DEC-94'',''DD-MON-RR''),6575734231,''pharez.christen@gmail.com'',358997647)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Armand'',''Konstantinas'',''73 Ramblewood Street'',''Apt 98'',''Boxborough'',67234,''IL'',to_date(''01-AUG-61'',''DD-MON-RR''),9845673256,''armand.konstantinas.1@gmail.com'',984567654)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Signy'',''Yudel'',''42 Rockland Ave'',''Apt 21'',''Littleon'',24645,''CO'',to_date(''03-NOV-85'',''DD-MON-RR''),7702340235,''yudel.sygny@gmail.com'',965735321)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Methusalem'',''Riley'',''890 Marconi Ave'',''Apt 2'',''Devens'',75234,''CO'',to_date(''31-JUL-66'',''DD-MON-RR''),3408438956,''riley.m@gmail.com'',523421567)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Roshni'',''Danjuma'',''340 Big Rock Cove Street'',''Apt 23'',''Groton'',46254,''AR'',to_date(''14-MAY-74'',''DD-MON-RR''),9875349561,''roshni.d@gmail.com'',686534575)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Reese'',''Elena'',''21 Lakeshore Street'',''Apt 6'',''Pepperell'',67357,''AK'',to_date(''08-NOV-88'',''DD-MON-RR''),9723467432,''elena.reese@gmail.com'',435645252)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Hanne'',''Enver'',''15 William Ave'',''Apt 9'',''Dunstable'',58776,''OR'',to_date(''12-JAN-03'',''DD-MON-RR''),9087254454,''enver.h@gmail.com'',757254865)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Balor'',''Rhiannon'',''8 Oakwood Drive'',''Apt 1'',''Nashua'',78347,''RI'',to_date(''18-OCT-83'',''DD-MON-RR''),9085752445,''rhiannon.b@gmail.com'',853457544)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Amirah'',''Golnaz'',''89 Hamilton Drive'',''Apt 5'',''Merrimack'',87544,''MA'',to_date(''30-NOV-97'',''DD-MON-RR''),8712647400,''golnaz.amirah@gmail.com'',854352325)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Jayesh'',''Jakhatiya'',''98 Carpenter Street'',''Apt 8'',''Manchester'',25990,''NH'',to_date(''10-MAY-96'',''DD-MON-RR''),8326459065,''jay.jakhatiya@gmail.com'',854654756)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Toki'',''Daniel'',''897 Nichols Street'',''Apt 24'',''Francestown'',24094,''NJ'',to_date(''20-FEB-79'',''DD-MON-RR''),3875046809,''toki.dan@gmail.com'',314345456)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Akanksha'',''Dubey'',''138 W Central Court'',''Apt 97'',''Bennington'',34890,''VA'',to_date(''31-MAR-72'',''DD-MON-RR''),8327584905,''adubey@gmail.com'',674255676)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Magdalena'',''Ildar'',''366 8th Street'',''Apt 59'',''Hancock'',24904,''VA'',to_date(''29-MAY-79'',''DD-MON-RR''),4856798256,''ildar.mag@gmail.com'',343254564)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Vladimiras'',''Nedyalka'',''1 Rockwell Street'',''Apt 23'',''Dublin'',67509,''VT'',to_date(''14-JAN-99'',''DD-MON-RR''),5907690776,''ned.vlad@gmail.com'',346576532)';
    EXECUTE IMMEDIATE 'INSERT INTO patient (FIRST_NAME,LAST_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,ZIP,STATE_NAME,DOB,CONTACT_NO,EMAIL_ID,SSN) values (''Paschal'',''Margarita'',''345 Manhattan Ave'',''Apt 2'',''Harrisville'',35909,''CT'',to_date(''29-SEP-01'',''DD-MON-RR''),6098435896,''margarita@gmail.com'',675653554)';

    DBMS_OUTPUT.PUT_LINE('PATIENT DATA INSERTION COMPLETED');
    
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'DOCTOR';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DOCTOR TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DOCTOR
            (	
            doctor_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY, 
            doc_first_name varchar2(50) NOT NULL,
            doc_last_name varchar2(50) NOT NULL,
            license_no number(7) not null,
            doc_address_line1 varchar2(50) NOT NULL,
            doc_address_line2 varchar2(50) NOT NULL,
            doc_city varchar2(20),
            doc_zip number(5) NOT NULL,
            doc_state_name varchar2(3),
            CONSTRAINT doc_restrict_ploc CHECK (doc_state_name IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')),
            CONSTRAINT doctor_id PRIMARY KEY(doctor_id)
            )';
    DBMS_OUTPUT.PUT_LINE('DOCTOR TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Dolores'',''Abernathy'',501,''16 Notre Dame'',''apt 1'',''Boston'',02119,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Bernard'',''lowe'',502,''17 center'',''apt 2'',''Boston'',02120,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Maeve'',''Millay'',503,''18 marcella'',''apt 3'',''Boston'',02121,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Teddy'',''Flood'',504,''19 forsyth'',''apt 4'',''Boston'',02122,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Robert'',''Ford'',505,''20 huntington ave'',''apt 5'',''Boston'',02123,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Angela'',''Sarafyan'',506,''21 Hemenway'',''apt 6'',''Boston'',02124,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Charlotte'',''Hale'',507,''22 Park'',''apt 7'',''Boston'',02125,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Caleb'',''Nichols'',508,''23 Fisher'',''apt 8'',''Boston'',02126,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''Lee'',''Sizemore'',509,''24 heath'',''apt 9'',''Boston'',02127,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name) values (''James'',''Delos'',510,''25 Cowing street'',''apt 10'',''Boston'',02128,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Val'',''Sparrow'',511,''759 Lantern Lane'',''Apt 98'',''Yorktown'',10598,''NY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Leah'',''Kate'',512,''3 Cherry Hill Street'',''Apt 13'',''Carmel'',10512,''NY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Ginnie'',''Kassie'',513,''7145 N. Heather Street'',''Apt 1'',''Douglasville'',81401,''GA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Jasmyn'',''Roxanne'',514,''8045 Linda Ave'',''Unit 212'',''Richardson'',29470,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Wendy'',''Wally'',515,''9331 Baker Lane'',''Unit 8'',''Hicksville'',17379,''NY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Hellen'',''Mya'',516,''279 Park Drive'',''Unit 24'',''Levittown'',11756,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Alaiya'',''Stanford'',517,''943 Arrowhead St'',''Apt 13'',''Wheeling'',43440,''FL'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Libby'',''Florence'',518,''632 East New Rd'',''Apt 73'',''Crystal Lake'',65722,''WY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Asia'',''Flower'',519,''7150 Maiden Road'',''Apt 24'',''Groton'',79703,''IL'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Tamsyn'',''Reese'',520,''986 South Sherman Dr'',''Apt 73'',''Lockport'',55753,''CT'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Dorothy'',''Jerrod'',521,''3 Mill Pond Road'',''Apt 63'',''Albany'',86732,''NY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Stephanie'',''Stefanos'',522,''91 Willow Street'',''Apt 23'',''Port Richey'',24540,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Elvina'',''Marrie'',523,''9461 Birchpond Lane'',''Apt 12'',''Windermere'',13340,''FL'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Landyn'',''Florry'',524,''81 N. Walnut Avenue'',''Apt 15'',''Loveland'',23416,''OH'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Kacey'',''Gerry'',525,''29 West Summer St.'',''Apt 10'',''Phillipsburg'',43113,''NJ'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Lachlan'',''Marietta'',526,''783 Argyle Street'',''Apt 4'',''Pawtucket'',64220,''RI'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Cherokee'',''Clarence'',527,''69 Hanover Drive'',''Apt 1'',''Smyrna'',21807,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Charlton'',''Shauna'',528,''341 North Rock Creek St.'',''Apt 9'',''Chesterfield'',13480,''OH'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Meagan'',''Meredith'',529,''629 Cobblestone Ave.'',''Apt 7'',''Lorton'',12950,''KY'')';
    EXECUTE IMMEDIATE 'INSERT INTO Doctor (DOC_FIRST_NAME,DOC_LAST_NAME,LICENSE_NO,DOC_ADDRESS_LINE1,DOC_ADDRESS_LINE2,DOC_CITY,DOC_ZIP,DOC_STATE_NAME) values (''Lennon'',''Xavier'',530,''902 S. Arrowhead Lane'',''Apt 3'',''Methuen'',12307,''WI'')';

    DBMS_OUTPUT.PUT_LINE('DOCTOR DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'HOSPITAL';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('HOSPITAL TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL
            (	
                hospital_id number GENERATED AS IDENTITY (START WITH 50 INCREMENT BY 1) primary key,
                hosp_name varchar2(50),
                hosp_address_line1 varchar2(50),
                hosp_address_line2 varchar2(50),
                hosp_city varchar2(20),
                hosp_zip number(5),
                hosp_state varchar2(3),
                CONSTRAINT hos_restrict_loc CHECK (hosp_state IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')))';
    DBMS_OUTPUT.PUT_LINE('HOSPITAL TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Apollo Hospital'', ''Smith St'',''Building 4'',''Boston'',02116,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Ruby Hospital'','' School St'',''4th lane'',''Boston'',02118,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Beth Isarel'', ''aphonsus street'',''Building 12'',''Boston'',02121,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''MASS general Hospital'', ''32 Fruit St'',''12th lane'',''Boston'',02114,''MA'')';

    DBMS_OUTPUT.PUT_LINE('HOSPITAL DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'DEPARTMENTS';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DEPARTMENTS TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DEPARTMENTS
            (	
                dept_id number GENERATED AS IDENTITY (START WITH 10 INCREMENT BY 20) primary key,
                dept_name varchar2(30) 
            )';
    DBMS_OUTPUT.PUT_LINE('DEPARTMENTS TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Critical Care'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Pediatrics'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Haematology'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Opthalmology'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Nursing'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Pathology'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Diagnostic Image'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Ortho'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Finance'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Accident and Emergency'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Anesthetics'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Health and Safety'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Cardiology'')';
    EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Psychology'')';
    DBMS_OUTPUT.PUT_LINE('DEPARTMENTS DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'HOSPITAL_DEPT';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL_DEPT 
            (	
                hos_dept_id number GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
                hospital_id number not null references hospital(hospital_id),
                dept_id number not null references departments(dept_id)
            )';
    DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,10)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,30)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,50)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,70)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,90)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,110)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,130)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,150)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,170)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,190)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,250)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,10)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,30)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,50)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,70)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,90)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,110)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,130)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,150)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,170)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,190)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (51,230)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,10)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,30)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,50)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,70)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,90)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,250)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,230)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,150)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,170)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,190)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (52,250)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,170)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,190)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,50)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,70)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,90)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,110)';
    EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (53,130)';
    
    DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'DOCTOR_HOSPITAL';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DOCTOR_HOSPITAL TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DOCTOR_HOSPITAL
            (	
                doc_hospital_id number GENERATED BY DEFAULT AS IDENTITY primary key,
                hos_dept_id number references hospital_dept (hos_dept_id),
                doctor_id number references doctor (doctor_id)
            )';
    DBMS_OUTPUT.PUT_LINE('DOCTOR_HOSPITAL TABLE CREATED');
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (1,1)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (12,1)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (23,1)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (1,5)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (12,5)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (23,5)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (2,2)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (13,2)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (24,2)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (2,6)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (13,6)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (24,6)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (3,3)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (14,3)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (25,3)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (36,3)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (4,4)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (15,4)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (26,4)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (37,4)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (5,7)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (16,7)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (27,7)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (38,7)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (6,8)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (17,8)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (39,8)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (6,9)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (17,9)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (39,9)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (6,10)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (17,10)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (39,10)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (7,11)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (18,11)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (40,11)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (7,12)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (18,12)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (40,12)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (8,13)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (19,13)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (30,13)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (8,14)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (19,14)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (30,14)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (10,15)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (21,15)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (32,15)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (35,15)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (10,16)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (21,16)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (32,16)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (35,16)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (22,17)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (29,17)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (22,18)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (29,18)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (11,19)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (28,19)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (33,19)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (11,20)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (28,20)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (33,20)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (11,21)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (28,21)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (33,21)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (3,22)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (14,22)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (25,22)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (36,22)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (4,23)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (15,23)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (26,23)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (37,23)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (5,24)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (16,24)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (27,24)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (38,24)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (6,25)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (17,25)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (39,25)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (6,26)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (17,26)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (39,26)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (7,27)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (18,27)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (40,27)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (8,28)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (19,28)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (30,28)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (10,29)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (21,29)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (32,29)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (35,29)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (11,30)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (28,30)';
    EXECUTE IMMEDIATE 'Insert into DOCTOR_HOSPITAL (HOS_DEPT_ID,DOCTOR_ID) values (33,30)';
    
    DBMS_OUTPUT.PUT_LINE('DOCTOR_HOSPITAL DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'PATIENT_HISTORY';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('PATIENT_HISTORY TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PATIENT_HISTORY
            (	
                file_id number GENERATED BY DEFAULT AS IDENTITY primary key,
                treatment varchar2(200),
                date_of_treatment date
            )';
    DBMS_OUTPUT.PUT_LINE('PATIENT_HISTORY TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO PATIENT_HISTORY(treatment,date_of_treatment) values (''Anthrax'',to_date(''11/19/2019'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Anthrax'',to_date(''23-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Blood Pressure'',to_date(''05-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Cholestrol'',to_date(''01-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Kidney stone'',to_date(''19-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Heart Transplant'',to_date(''01-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Back pain'',to_date(''30-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Arthritis'',to_date(''06-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''01-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Routine checkup'',to_date(''24-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Alleric reaction'',to_date(''13-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Appendicitis'',to_date(''17-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Fracture'',to_date(''03-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''30-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''11-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Blood Pressure'',to_date(''09-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Cholestrol'',to_date(''17-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Kidney stone'',to_date(''06-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Heart Transplant'',to_date(''20-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Back pain'',to_date(''14-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''X-ray'',to_date(''03-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Burns'',to_date(''21-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Arthritis'',to_date(''17-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''29-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''General checkup'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''22-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''29-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Fracture'',to_date(''08-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Burns'',to_date(''04-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Appendicitis'',to_date(''07-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''X-Ray'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Alleric reaction'',to_date(''03-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''06-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''03-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Routine checkup'',to_date(''23-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Alleric reaction'',to_date(''20-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Appendicitis'',to_date(''03-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Fracture'',to_date(''11-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''04-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Blood Pressure'',to_date(''13-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Cholestrol'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Kidney stone'',to_date(''28-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Heart Transplant'',to_date(''12-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Back pain'',to_date(''09-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''X-ray'',to_date(''27-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Burns'',to_date(''15-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Arthritis'',to_date(''21-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''29-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''General checkup'',to_date(''20-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''27-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''20-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''05-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Routine checkup'',to_date(''11-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Alleric reaction'',to_date(''15-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Appendicitis'',to_date(''30-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Fracture'',to_date(''07-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''23-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''26-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Blood Pressure'',to_date(''05-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Cholestrol'',to_date(''05-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Kidney stone'',to_date(''24-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Heart Transplant'',to_date(''09-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Back pain'',to_date(''10-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''X-ray'',to_date(''22-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Burns'',to_date(''28-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Arthritis'',to_date(''26-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''07-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''General checkup'',to_date(''05-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''29-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''04-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Routine checkup'',to_date(''02-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Alleric reaction'',to_date(''06-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Appendicitis'',to_date(''31-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Fracture'',to_date(''23-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''04-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''29-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Blood Pressure'',to_date(''13-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Cholestrol'',to_date(''20-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Kidney stone'',to_date(''07-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Heart Transplant'',to_date(''03-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Back pain'',to_date(''28-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''X-ray'',to_date(''18-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Burns'',to_date(''17-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Arthritis'',to_date(''27-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''11-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''General checkup'',to_date(''29-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Influenza'',to_date(''19-APR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Conjunctivitis'',to_date(''20-MAR-22'',''DD-MON-RR''))';
    EXECUTE IMMEDIATE 'Insert into PATIENT_HISTORY(TREATMENT,DATE_OF_TREATMENT) values (''Eye checkup'',to_date(''01-APR-22'',''DD-MON-RR''))';
    DBMS_OUTPUT.PUT_LINE('PATIENT_HISTORY DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'PATIENT_DOCUMENT';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('PATIENT_DOCUMENT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PATIENT_DOCUMENT
            (	
                patient_file_id number GENERATED BY DEFAULT AS IDENTITY primary key,
                patient_id number references patient (patient_id),
                file_id number references patient_history (file_id)
            )';
    DBMS_OUTPUT.PUT_LINE('PATIENT_DOCUMENT TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO PATIENT_DOCUMENT(patient_id,file_id) values (1,1)';
    DBMS_OUTPUT.PUT_LINE('PATIENT_DOCUMENT DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'DOC_AVAILABILITY';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DOC_AVAILABILITY TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DOC_AVAILABILITY
            (	
                avail_id number GENERATED AS IDENTITY (START WITH 01 INCREMENT BY 1) primary key,
                doctor_id number references doctor(doctor_id),
                day varchar2(3),
                start_time timestamp, 
                end_time timestamp
            )';
    DBMS_OUTPUT.PUT_LINE('DOC_AVAILABILITY TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (1,''MON'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (1,''TUE'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (1,''WED'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (1,''THU'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (1,''FRI'',TO_TIMESTAMP(''13:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (2,''MON'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (2,''TUE'',TO_TIMESTAMP(''14:00'',''hh24:mi''),TO_TIMESTAMP(''20:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (2,''WED'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (2,''THU'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (2,''FRI'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''16:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (3,''MON'',TO_TIMESTAMP(''08:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (3,''TUE'',TO_TIMESTAMP(''08:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (3,''WED'',TO_TIMESTAMP(''15:00'',''hh24:mi''),TO_TIMESTAMP(''19:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (3,''THU'',TO_TIMESTAMP(''15:00'',''hh24:mi''),TO_TIMESTAMP(''19:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (3,''FRI'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''13:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (4,''MON'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (4,''TUE'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (4,''WED'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (4,''THU'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (4,''FRI'',TO_TIMESTAMP(''13:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (5,''MON'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''20:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (5,''TUE'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''16:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (5,''WED'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''17:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (5,''THU'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''15:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (5,''FRI'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''13:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (6,''MON'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (6,''TUE'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (6,''FRI'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (6,''MON'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (6,''THU'',TO_TIMESTAMP(''13:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (7,''TUE'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (7,''WED'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (7,''THU'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (8,''MON'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (8,''THU'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';

    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (8,''FRI'',TO_TIMESTAMP(''14:00'',''hh24:mi''),TO_TIMESTAMP(''20:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (9,''TUE'',TO_TIMESTAMP(''09:00'',''hh24:mi''),TO_TIMESTAMP(''16:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (9,''WED'',TO_TIMESTAMP(''14:00'',''hh24:mi''),TO_TIMESTAMP(''20:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (9,''THU'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (9,''FRI'',TO_TIMESTAMP(''13:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (10,''MON'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (10,''TUE'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (10,''WED'',TO_TIMESTAMP(''10:00'',''hh24:mi''),TO_TIMESTAMP(''14:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (10,''THU'',TO_TIMESTAMP(''12:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';
    EXECUTE IMMEDIATE 'INSERT INTO DOC_AVAILABILITY(doctor_id,day,start_time,end_time) values (10,''FRI'',TO_TIMESTAMP(''13:00'',''hh24:mi''),TO_TIMESTAMP(''18:00'',''hh24:mi''))';

    DBMS_OUTPUT.PUT_LINE('DOC_AVAILABILITY DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'APPOINTMENTS';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('APPOINTMENTS TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE APPOINTMENTS
            (	
                appointment_id number GENERATED AS IDENTITY (START WITH 20 INCREMENT BY 1) primary key,
                apmt_date date,
                doc_hospital_id number references doctor_hospital(doc_hospital_id),
                file_id number references patient_history(file_id),
                start_time timestamp
            )';
    DBMS_OUTPUT.PUT_LINE('APPOINTMENTS TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO APPOINTMENTS(apmt_date,doc_hospital_id,file_id,start_time) values (TO_DATE(''2022/04/04'', ''yyyy/mm/dd''),1,1,TO_TIMESTAMP(''10:00'',''hh24:mi''))';
    DBMS_OUTPUT.PUT_LINE('APPOINTMENTS DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'VACCINE';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('VACCINE TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE VACCINE 
            (	
                vaccine_id number GENERATED AS IDENTITY (START WITH 001 INCREMENT BY 2) primary key,
                vaccine_name varchar2(20),
                inoculated_by_days number
            )';
    DBMS_OUTPUT.PUT_LINE('VACCINE TABLE CREATED');
    
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Pfizer-Covid'',150)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Moderna-Covid'',30)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''JJ-Covid'',60)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Influenza'',180)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''MMR'',5)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Typhoid'',3)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Hepatitis A'',30)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Hepatitis B'',90)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Diphtheria'',15)';
    EXECUTE IMMEDIATE 'Insert into VACCINE (VACCINE_NAME,INOCULATED_BY_DAYS) values (''Tetanus'',10)';

    DBMS_OUTPUT.PUT_LINE('VACCINE DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'VACCINE_RECORDS';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('VACCINE_RECORDS TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE VACCINE_RECORDS  
            (	
                record_id number GENERATED AS IDENTITY primary key,
                patient_id number references patient(patient_id),
                vaccine_id number references vaccine(vaccine_id),
                date_of_vaccination date
            )';
    DBMS_OUTPUT.PUT_LINE('VACCINE_RECORDS TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,1,to_date(''04/04/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,7,to_date(''03/23/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,9,to_date(''02/13/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,7,to_date(''04/30/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,13,to_date(''01/12/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,15,to_date(''04/26/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (1,13,to_date(''02/11/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,1,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,1,to_date(''04/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,19,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,15,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,7,to_date(''12/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,7,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,9,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,11,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (2,13,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (3,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (3,17,to_date(''08/23/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (3,15,to_date(''12/31/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (3,13,to_date(''06/23/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (3,13,to_date(''08/08/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,1,to_date(''01/26/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,13,to_date(''03/19/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,15,to_date(''02/20/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,7,to_date(''04/10/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,1,to_date(''02/20/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,3,to_date(''04/21/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,11,to_date(''10/30/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (4,17,to_date(''12/02/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (5,3,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (5,3,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (5,7,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,9,to_date(''08/08/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,11,to_date(''01/08/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,13,to_date(''01/04/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,11,to_date(''05/02/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,15,to_date(''01/02/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,13,to_date(''02/24/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,17,to_date(''04/26/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,19,to_date(''01/29/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,19,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (6,9,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (7,5,to_date(''03/01/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (7,5,to_date(''04/03/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (7,9,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (7,11,to_date(''05/02/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,1,to_date(''01/24/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,1,to_date(''03/24/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,9,to_date(''02/23/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,9,to_date(''04/05/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,13,to_date(''11/08/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,13,to_date(''02/18/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (8,17,to_date(''04/02/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,17,to_date(''08/08/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,17,to_date(''04/13/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,5,to_date(''02/10/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,5,to_date(''04/15/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,11,to_date(''08/30/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,19,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,11,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,13,to_date(''01/18/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,13,to_date(''03/28/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (9,7,to_date(''07/02/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (10,1,to_date(''08/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,1,to_date(''02/28/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,1,to_date(''04/24/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,3,to_date(''03/30/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,5,to_date(''01/27/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,7,to_date(''03/24/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,9,to_date(''07/21/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,11,to_date(''03/31/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,13,to_date(''11/12/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (11,15,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,1,to_date(''07/04/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,1,to_date(''10/30/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,7,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,9,to_date(''09/03/2021'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,15,to_date(''03/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,17,to_date(''02/08/2022'',''mm/dd/yyyy''))';
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE_RECORDS(patient_id,vaccine_id,date_of_vaccination) values (12,19,to_date(''01/08/2022'',''mm/dd/yyyy''))';
    
    DBMS_OUTPUT.PUT_LINE('VACCINE_RECORDS DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'COVERAGE';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('COVERAGE TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE COVERAGE   
            (	
                coverage_id number generated AS identity (start with 15000 increment by 11) primary key,
                plan_name varchar2(100),
                health_inclusive varchar2(100),
                dental_inclusive varchar2(100),
                premium number
            )';
    DBMS_OUTPUT.PUT_LINE('COVERAGE TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Silver'',''Y'',''N'',2400)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Silver'',''Y'',''N'',2700)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Gold'',''Y'',''Y'',3500)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Gold'',''Y'',''Y'',3800)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Platinum'',''Y'',''N'',5000)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Platinum'',''Y'',''Y'',4800)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Diamond'',''Y'',''Y'',6500)';
    EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium) values(''Diamond'',''Y'',''Y'',6700)';

    DBMS_OUTPUT.PUT_LINE('COVERAGE DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'INSURANCE_PROVIDER';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER TABLE ALREADY EXISTS');

ELSE EXECUTE IMMEDIATE 'CREATE TABLE INSURANCE_PROVIDER   
            (	
                provider_id number generated AS identity (start with 1 increment by 1) primary key,
                provider_name varchar2(100),
                provider_address_line1 varchar2(100),
                provider_address_line2 varchar2(100),
                provider_city varchar2(20),
                provider_zip number,
                provider_state varchar2(20)
            )';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Blue Cross Blue Shield'',''360 Atlantic Ave'',''Suite 1'',''Boston'',02142,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Reinsurance'',''786 Mass Avenue'',''office-35'',''Boston'',09846,''MA'')';
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Aetna'',''Manhattan Boulevard'',''Office-5'',''Manhattan'',02446,''NY'')';
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Kaiser Foundation Health Plan'',''4 Chester Spring'',''Charlie Street'',''Exton'',00046,''PA'')';
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Cigna'',''4 Bloomfield'',''Charlie Street'',''Connecticut'',00046,''PA'')';
    
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'INSURANCE_PLAN';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE INSURANCE_PLAN   
            (	
                plan_id number generated as identity (start with 10 increment by 5) primary key,
                coverage_id number references coverage (coverage_id),
                provider_id number references insurance_provider (provider_id)
            )';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15000,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15011,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15022,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15033,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15044,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15055,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15066,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15077,1)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15000,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15011,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15022,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15033,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15044,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15055,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15066,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15077,2)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15000,3)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15022,3)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15044,3)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15066,3)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15011,4)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15033,4)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15055,4)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15077,4)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15000,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15011,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15022,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15033,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15033,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15044,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15055,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15066,5)';
    EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15077,5)';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'BILLING';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('BILLING TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE BILLING  
            (	
                bill_no number GENERATED AS IDENTITY (START WITH 10000 INCREMENT BY 1) primary key,
                amount number,
                appointment_id number references appointments(appointment_id)
            )';
    DBMS_OUTPUT.PUT_LINE('BILLING TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO BILLING (amount,appointment_id) values (1500,20)';
    DBMS_OUTPUT.PUT_LINE('BILLING DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'RECEIPT';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('RECEIPT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE RECEIPT  
            (	
                receipt_no NUMBER GENERATED AS IDENTITY (START WITH 1000 INCREMENT BY 3) primary key,
                date_of_payment date,
                bill_no number references Billing(bill_no)
            )';
    DBMS_OUTPUT.PUT_LINE('RECEIPT TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO RECEIPT (date_of_payment,bill_no) values (TO_DATE(''2022/04/04'', ''yyyy/mm/dd''),10000)';
    DBMS_OUTPUT.PUT_LINE('RECEIPT DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'INSURANCE_POLICY';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('INSURANCE_POLICY TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE INSURANCE_POLICY
        (	
                policy_id number generated as identity (start with  1000000 increment by 1) primary key,
                pol_start_date date,
                pol_end_date date,
                duration_months number,
                patient_copays number,
                premium_payment_option VARCHAR2(5),
                premium_due_date date,
                plan_id number references insurance_plan(plan_id)
            )';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_POLICY TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_POLICY(pol_start_date,pol_end_date,duration_months,patient_copays,premium_payment_option,premium_due_date,plan_id) values (to_date(''04/01/2019'',''mm/dd/yyyy''),to_date(''03/31/2023'',''mm/dd/yyyy''),20,100,''QUART'',to_date(''06/30/2022'',''mm/dd/yyyy''),10)';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_POLICY DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'PATIENT_POLICY';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('PATIENT_POLICY TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PATIENT_POLICY   
            (	
                patient_policy_id number generated AS identity (start with 300000 increment by 1) primary key,
                policy_id number references INSURANCE_POLICY(policy_id),
                patient_id number references patient(patient_id)
            )';
    DBMS_OUTPUT.PUT_LINE('PATIENT_POLICY TABLE CREATED'); 
    
    EXECUTE IMMEDIATE 'INSERT INTO PATIENT_POLICY(policy_id,patient_id) values (1000000,1)';
    DBMS_OUTPUT.PUT_LINE('PATIENT_POLICY DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'PREMIUM_PAYMENTS';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('PREMIUM_PAYMENTS TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PREMIUM_PAYMENTS    
            (	
                premium_bill_no number generated as identity (start with 200 increment BY 2) primary key,
                policy_id number references INSURANCE_POLICY(policy_id),
                receipt_no NUMBER references receipt(receipt_no)
            )';
    DBMS_OUTPUT.PUT_LINE('PREMIUM_PAYMENTS TABLE CREATED'); 
    
    EXECUTE IMMEDIATE 'INSERT INTO PREMIUM_PAYMENTS(policy_id,receipt_no) values (1000000,1000)';
    DBMS_OUTPUT.PUT_LINE('PREMIUM_PAYMENTS DATA INSERTION COMPLETED');
END IF;

COMMIT;

END;

/
