SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;

BEGIN

SELECT count(*) into nCount FROM user_tables where table_name = 'PATIENT';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('PATIENT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE PATIENT
            (	
            patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
            first_name varchar2(50) NOT NULL,
            last_name varchar2(50) NOT NULL,
            address_line1 varchar2(50) NOT NULL,
            address_line2 varchar2(50) NOT NULL,
            city varchar2(20),
            zip number(5) NOT NULL,
            state_name varchar2(3),
            DOB date,
            contact_no number(10),
            email_id VARCHAR2(40),
            SSN number(9) NOT NULL,
            CONSTRAINT restrict_ploc CHECK (state_name IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')),
            CONSTRAINT patient_id PRIMARY KEY(patient_id),
            CONSTRAINT ssn_unique UNIQUE(SSN),
            CONSTRAINT email_chk CHECK (email_id LIKE ''%@%.%'' AND email_id NOT LIKE ''@%'' AND email_id NOT LIKE ''%@%@%'')
            )';
    DBMS_OUTPUT.PUT_LINE('PATIENT TABLE CREATED');
    
   -----------patient insertions------------------
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''tina'',''natekar'',''2 torpie street'',''apt-1'',''boston'',02120,''MA'',TO_DATE(''1998/06/03'', ''yyyy/mm/dd''),4766443677,''tina@gmail.com'',312829898)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''miranda'',''tate'',''89 Huntington street'',''apt-13'',''Dayton'',021320,''OH'',to_date(''03.02.1988'',''mm/dd/yyyy''),4762134677,''MIR@gmail.com'',1228);)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''nina'',''dobrev'',''smith street'',''apt-3'',''boston'',98765,''MA'',to_date(''08.12.1991'',''mm/dd/yyyy''),8576423132,''nina@gmail.com'',348576338)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''tyler'',''smith'',''56 va medical center'',''apt-89'',''baltimore'',01115,''MY'',to_date(''01.08.1998'',''mm/dd/yyyy''),8573179680,''smith@gmail.com'',294755093)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''steve'',''warner'',''13 heath street'',''apt-46'',''boston'',09800,''MA'',to_date(''01.06.1989'',''mm/dd/yyyy''),5642356446,''steve@gmail.com'',4857647657)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''marcus'',''stoinis'',''10 horadon way'',''apt-199'',''houston'',01219,''TX'',to_date(''01.03.1991'',''mm/dd/yyyy''),9877746536,''ms@gmail.com'',498570909)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''jaina'',''abideen'',''988 gargoil street'',''apt-76'',''san diego'',028810,''CA'',to_date(''09.10.2001'',''mm/dd/yyyy''),992292250,''jainahero@gmail.com'',948567878)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''ross'',''gallor'',''1 hemenway street'',''apt-34'',''boston'',02115,''MA'',to_date(''12.12.1988'',''mm/dd/yyyy''),7566677769,''ross@yahoo.com'',298341198)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''virat'',''kohli'',''75 st alhonsus'',''apt-816'',''boston'',02120,''MA'',to_date(''09.30.1998'',''mm/dd/yyyy''),3571536757,''virat70@gmail.com'',198342541)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Thibau'',''courtouis'',''13 santiago bernabeu street'',''apt-1'',''roxbury'',02119,''MA'',to_date(''12.19.1987'',''mm/dd/yyyy''),6179924681,''t.coutouis@outlook.com'',984561901)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''David'',''Alaba'',''04 wakulah street'',''apt-13'',''boston'',02120,''MA'',to_date(''09.09.1985'',''mm/dd/yyyy''),9443916852,''david04@yahoo.co.in'',2004)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Eder'',''Militao'',''22 washington street'',''apt-29'',''Roxbury'',02119,''MA'',to_date(''06.24.1992'',''mm/dd/yyyy''),9443442747,''edermilitao0335@gmail.com'',487561517)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Ferland'',''Mendy'',''44 park drive street'',''apt-3'',''boston'',98765,''MA'',to_date(''04.21.1992'',''mm/dd/yyyy''),9486612364,''mendy.f@realmadrid.com'',983210908)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Dani'',''Carvajal'','' 02 bay state place'',''apt-2014'',''boston'',02127,''MA'',to_date(''05.17.1998'',''mm/dd/yyyy''),9443913624,''danic2@gmail.com'',0990)';
EXECUTE IMMEDIATE 'INSERT INTO patient (first_name,last_name,address_line1,address_line2,city,zip,state_name,DOB,contact_no,email_id,SSN) VALUES (''Tony'',''Kroos'',''13 heath street'',''apt-23'',''boston'',02120,''MA'',to_date(''06.14.1974'',''mm/dd/yyyy''),9443321323,''kroos_toni8@gmail.com'',7986)';
DBMS_OUTPUT.PUT_LINE('PATIENT DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'DOCTOR';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DOCTOR TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DOCTOR
            (	
            doctor_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY, 
            doc_first_name varchar2(50) NOT NULL,
            doc_last_name varchar2(50) NOT NULL,
            license_no number(7) not null,
            doc_address_line1 varchar2(50) NOT NULL,
            doc_address_line2 varchar2(50) NOT NULL,
            doc_city varchar2(20),
            doc_zip number(5) NOT NULL,
            doc_state_name varchar2(3),
            CONSTRAINT doc_restrict_ploc CHECK (doc_state_name IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')),
            CONSTRAINT doctor_id PRIMARY KEY(doctor_id)
            )';
    DBMS_OUTPUT.PUT_LINE('DOCTOR TABLE CREATED');
    
    ---------------doctor insertions-----------------------
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Dolores'',''Abernathy'',501,''16 Notre Dame'',''apt 1'',''Boston'',02119,''MA'')';   
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Bernard'',''lowe'',502,''17 center'',''apt 2'',''Boston'',02120,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Maeve'',''Millay'',503,''18 marcella'',''apt 3'',''Boston'',02121,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Teddy'',''Flood'',504,''19 forsyth'',''apt 4'',''Boston'',02122,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Robert'',''Ford'',505,''20 huntington ave'',''apt 5'',''Boston'',02123,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Angela'',''Sarafyan'',506,''21 Hemenway'',''apt 6'',''Boston'',02124,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Charlotte'',''Hale'',507,''22 Park'',''apt 7'',''Boston'',02125,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Caleb'',''Nichols'',508,''23 Fisher'',''apt 8'',''Boston'',02126,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''Lee'',''Sizemore'',509,''24 heath'',''apt 9'',''Boston'',02127,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO Doctor (doc_first_name,doc_last_name,license_no,doc_address_line1,doc_address_line2,doc_city,doc_zip,doc_state_name,ssn) values (''James'',''Delos'',510,''25 Cowing street'',''apt 10'',''Boston'',02128,''MA'')';
 DBMS_OUTPUT.PUT_LINE('DOCTOR DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'HOSPITAL';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('HOSPITAL TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL
            (	
                hospital_id number GENERATED AS IDENTITY (START WITH 50 INCREMENT BY 1) primary key,
                hosp_name varchar2(50),
                hosp_address_line1 varchar2(50),
                hosp_address_line2 varchar2(50),
                hosp_city varchar2(20),
                hosp_zip number(5),
                hosp_state varchar2(3),
                CONSTRAINT hos_restrict_loc CHECK (hosp_state IN (''AK'',''AZ'',''AR'',''CA'',''CO'',''CT'',''DE'',''FL'',
            ''GA'',''HI'',''ID'',''IL'',''IN'',''IA'',''KS'',''KY'',''LA'',''ME'',''MD'',''MA'',''MI'',''MN'',''MS'',''MO'',''MT'',''NE'',
            ''NV'',''NH'',''NJ'',''NM'',''NY'',''NC'',''ND'',''OH'',''OK'',''OR'',''PA'',''RI'',''SC'',''SD'',''TN'',''TX'',''UT'',''VT'',
            ''VA'',''WA'',''WV'',''WI'',''WY'')))';
    DBMS_OUTPUT.PUT_LINE('HOSPITAL TABLE CREATED');
    
    -----------------hospital insertions--------------------------
EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Apollo Hospital'', ''Smith St'',''Building 4'',''Boston'',02116,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Ruby Hospital'','' School St'',''4th lane'',''Boston'',02118,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''Beth Isarel'', ''aphonsus street'',''Building 12'',''Boston'',02121,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO hospital(hosp_name,hosp_address_line1,hosp_address_line2,hosp_city,hosp_zip,hosp_state) values (''MASS general Hospital'', ''32 Fruit St'',''12th lane'',''Boston'',02114,''MA'')';
                    DBMS_OUTPUT.PUT_LINE('HOSPITAL DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'DEPARTMENTS';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('DEPARTMENTS TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE DEPARTMENTS
            (	
                dept_id number GENERATED AS IDENTITY (START WITH 10 INCREMENT BY 20) primary key,
                dept_name varchar2(20) 
            )';
    DBMS_OUTPUT.PUT_LINE('DEPARTMENTS TABLE CREATED');
    
    --------------------department insertions----------------------                    
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Radiology'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''pediatrics'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Hematology'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Opthalmology'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Nursing'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Pathology'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Diagnostic Image'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''ortho'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Finance'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''multi speciality'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''Health & Safety'')';
EXECUTE IMMEDIATE 'INSERT INTO DEPARTMENTS(dept_name) values (''ENT'')';
DBMS_OUTPUT.PUT_LINE('DEPARTMENTS DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'HOSPITAL_DEPT';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL_DEPT 
            (	
                hos_dept_id number GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
                hospital_id number not null references hospital(hospital_id),
                dept_id number not null references departments(dept_id)
            )';
    DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT TABLE CREATED');
    
    -----------------hospital_dept insertions----------------------
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (50,10)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (120,30)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (30,50)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (290,450)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (230,140)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (340,10)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (187,14)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (32,15)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (94,16)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (89,23)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (39,34)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (71,56)';
EXECUTE IMMEDIATE 'INSERT INTO HOSPITAL_DEPT(hospital_id,dept_id) values (123,99)'; 
DBMS_OUTPUT.PUT_LINE('HOSPITAL_DEPT DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'VACCINE';

IF(nCount > 0) THEN
    DBMS_OUTPUT.PUT_LINE('VACCINE TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE VACCINE 
            (	
                vaccine_id number GENERATED AS IDENTITY (START WITH 001 INCREMENT BY 2) primary key,
                vaccine_name varchar2(20),
                inoculated_by_days number
            )';
    DBMS_OUTPUT.PUT_LINE('VACCINE TABLE CREATED');
    
    EXECUTE IMMEDIATE 'INSERT INTO VACCINE(vaccine_name,inoculated_by_days) values (''pfizer'',75)';
    DBMS_OUTPUT.PUT_LINE('VACCINE DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'COVERAGE';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('COVERAGE TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE COVERAGE   
            (	
                coverage_id number generated AS identity (start with 15000 increment by 11) primary key,
                plan_name varchar2(100),
                health_inclusive varchar2(100),
                dental_inclusive varchar2(100),
                premium number
            )';
    DBMS_OUTPUT.PUT_LINE('COVERAGE TABLE CREATED');
    
    -----------------coverage insertions----------------------------------
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''silver'',''Y'',''N'',2400)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Gold'',''Y'',''N'',3500)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Platinum'',''Y'',''Y'',5000)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Diamond'',''Y'',''Y'',6500)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Silver'',''Y'',''N'',2400)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Gold'',''Y'',''N'',3200)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Platinum'',''Y'',''Y'',4800)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Diamond'',''Y'',''Y'',6700)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Platinum'',''Y'',''Y'',5200)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''Gold'',''N'',''N'',3600)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''silver'',''Y'',''N'',2400)';
EXECUTE IMMEDIATE 'INSERT INTO COVERAGE(plan_name,health_inclusive,dental_inclusive,premium)values(''silver'',''Y'',''N'',2400)';
DBMS_OUTPUT.PUT_LINE('COVERAGE DATA INSERTION COMPLETED');
END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'INSURANCE_PROVIDER';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER TABLE ALREADY EXISTS');

ELSE EXECUTE IMMEDIATE 'CREATE TABLE INSURANCE_PROVIDER   
            (	
                provider_id number generated AS identity (start with 1 increment by 1) primary key,
                provider_name varchar2(100),
                provider_address_line1 varchar2(100),
                provider_address_line2 varchar2(100),
                provider_city varchar2(20),
                provider_zip number,
                provider_state varchar2(20)
            )';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER TABLE CREATED');
    
    -----------insurance insertions------------------
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Blue Cross Blue Shield'',''360 Atlantic Ave'',''Suite 1'',''Boston'',02142,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''reinsurance'', ''786 mass avenue'', ''office-35'',''boston'',09846,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''bcbs'', ''Manhattan Boulevard'',''office-5'',''Manhattan'',02446,''NY'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Blue Cross Blue Shield'',''303 southuntington Ave'',''office 20'',''Boston'',02120,''MA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''bcbs'', ''10 horadon way'',''Suite-199'',''houston'',01219,''TX'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''reinsurance'', ''988 gargoil street'',''apt-76'',''san diego'',028810,''CA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Aetna'', ''1 American Way'',''building 5'',''Santa Ana'',92707,''CA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Cigna'', ''519 Cumberland'',''Ave 1#'',''Portland'',04101,''ME'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Anthem'', ''98 Victoria Ave'',''office 34'',''Cranston'',02920,''RI'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Blue Shield of California'',''1337 N San Joaquin St'',''build 3'',''Stockton'',95202,''CA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Humana'', ''9851 South Redwood Street'',''apt 103'',''Titusville'',32780,''FL'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''TATA AIG'', ''2 E 41ST'',''Suite 1'',''BAYONNE'',0024803,''NJ'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Kaiser Permanente'', ''317 Fairchild Dr'',''Suite 1'',''Travis Afb'',94535,''CA'')';
EXECUTE IMMEDIATE 'INSERT INTO INSURANCE_PROVIDER(provider_name,provider_address_line1,provider_address_line2,provider_city,provider_zip,provider_state) VALUES (''Molina Healthcare'', ''197 Summerhouse Rd'',''Suite 231'',''Hollywood'',33024,''FL'')';
DBMS_OUTPUT.PUT_LINE('INSURANCE_PROVIDER DATA INSERTION COMPLETED');
END IF;


SELECT count(*) into nCount FROM user_tables where table_name = 'INSURANCE_PLAN';

IF(nCount > 0) THEN 
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN TABLE ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE TABLE INSURANCE_PLAN   
            (	
                plan_id number generated as identity (start with 10 increment by 5) primary key,
                coverage_id number references coverage (coverage_id),
                provider_id number references insurance_provider (provider_id)
            )';
    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN TABLE CREATED');
    
------------------insurance plan-----------------------------------------
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (15000,1)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3012,4001)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3013,4031)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3015,4501)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3016,6401)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3017,4701)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3018,4051)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3019,4401)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3020,4021)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3021,4801)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3022,4091)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3023,4704)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3024,4151)';
EXECUTE IMMEDIATE 'INSERT INTO insurance_plan (coverage_id,provider_id) values (3025,4265)';

    DBMS_OUTPUT.PUT_LINE('INSURANCE_PLAN DATA INSERTION COMPLETED');
END IF;





    
--    EXECUTE IMMEDIATE q'[INSERT INTO MASTER_TABLE VALUES ('RECIEPT','CREATE TABLE RECIEPT  
--            (	
--                reciept_no NUMBER GENERATED AS IDENTITY (START WITH 1000 INCREMENT BY 3) primary key,
--                date_of_payment date,
--                bill_no number references Billing (bill_no)
--            )
--    ')]';

COMMIT;

END;
